os:
  - linux
language: go
go:
  - 1.9
sudo: required

services:
  - docker
  - elasticsearch

cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/src/github.com/bmeg/arachne/.git/modules
    - $GOPATH/src/github.com/bmeg/arachne/vendor

git:
  submodules: false

# install RocksDB
before_install:

install:
  - make depends
  - make

jobs:
  include:
    - stage: all
      script: make lint
      env:
        - n=lint
    - script:
      - make test
      env:
        - n=tests
    - script:
      - arachne server --rpc 18202 --port 18201 &
      - sleep 5
      - make test-conformance
      - go test ./test -db badger
      env:
        - n=badger
    - script:
      - arachne server --rpc 18202 --port 18201 --bolt arachne.db &
      - sleep 5
      - make test-conformance
      - go test ./test -db bolt
      env:
        - n=boltdb
    - script:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get install libsnappy-dev zlib1g-dev libbz2-dev -qq

        - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags2_2.0-1.1ubuntu1_amd64.deb
        - sudo dpkg -i libgflags2_2.0-1.1ubuntu1_amd64.deb
        - wget https://launchpad.net/ubuntu/+archive/primary/+files/libgflags-dev_2.0-1.1ubuntu1_amd64.deb
        - sudo dpkg -i libgflags-dev_2.0-1.1ubuntu1_amd64.deb

        - git clone https://github.com/facebook/rocksdb.git /tmp/rocksdb
        - pushd /tmp/rocksdb
        - sudo make static_lib
        - sudo cp --preserve=links ./librocksdb.* /usr/lib/
        - sudo cp -r ./include/rocksdb/ /usr/include/
        - popd

        - make with-rocksdb
        - arachne server --rpc 18202 --port 18201 --rocks arachne.db &
        - sleep 5
        - make test-conformance
        - go test ./test -db rocks
      env:
        - n=rocksdb
    - script:
      - arachne server --rpc 18202 --port 18201 --level arachne.db &
      - sleep 5
      - make test-conformance
      - go test ./test -db level
      env:
        - n=leveldb
    - script:
      - make start-test-mongo-database
      - sleep 5
      - arachne server --rpc 18202 --port 18201 --mongo localhost:27000 &
      - sleep 5
      - make test-conformance
      env:
        - n=mongodb
    - script:
      - arachne server --rpc 18202 --port 18201 --elastic http://localhost:9200 &
      - sleep 5
      - make test-conformance
      env:
        - n=elasticsearch

notifications:
  email: false
